electrum:
  cd electrum && cargo run --bin electrum

esplora:
  cd esplora && cargo run --bin esplora

bitcoind:
  cd bitcoind-rpc && cargo run --bin bitcoind_rpc

architecture:
  cd architecture && cargo run --bin architecture

descriptors:
  cd descriptors && cargo run --bin descriptors
