[package]
name = "starter-example"
version = "0.1.0"
edition = "2021"

[dependencies]
bdk_wallet = { version = "2.2.0", features = ["rusqlite"] }
bdk_esplora = { version = "0.22.1", features = ["blocking"] }
