[package]
name = "starter-example"
version = "0.1.0"
edition = "2021"

[dependencies]
bdk_wallet = { version = "1.1.0", features = ["rusqlite"] }
bdk_esplora = { version = "0.20.1", features = ["blocking"] }
