[package]
name = "kyoto"
version = "0.1.0"
edition = "2021"

[dependencies]
bdk_kyoto = { version = "0.13.1" }
bdk_wallet = { version = "2.1.0" }
tokio = { version = "1", features = ["full"], default-features = false }
tracing = { version = "0.1" }
tracing-subscriber = { version = "0.3" }
