@default:
  just --list

fullwallet:
  cd fullwallet/ && cargo run --bin fullwallet

sync-electrum:
  cd syncing/electrum/ && cargo run --bin electrum

sync-esplora:
  cd syncing/esplora/ && cargo run --bin esplora

sync-rpc:
  cd syncing/rpc/ && cargo run --bin rpc

architecture:
  cd architecture/ && cargo run --bin architecture

descriptors:
  cd descriptors/ && cargo run --bin descriptors
