[workspace]
resolver = "2"
members = [
    "descriptors", "full-wallet", "migrate-version", "quickstart", "seed-phrase",
    "syncing/electrum", "syncing/esplora", "syncing/kyoto", "syncing/rpc",
    "persistence/memory", "persistence/sqlite"
]

[workspace.package]
authors = ["Bitcoin Dev Kit Developers"]