name: Rust examples checks
on: [push, pull_request, workflow_dispatch]

jobs:
  build_examples:
    name: Build Rust examples
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./examples/rust/
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.7.5
      - name: "Build all examples"
        run: cargo build

  fmt_check:
    name: Rust fmt check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./examples/rust/
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
          components: rustfmt
      - name: Check fmt
        run: cargo fmt --all -- --config format_code_in_doc_comments=true --check

  clippy_check:
    name: Rust clippy check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./examples/rust/
    permissions:
      checks: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
          override: true
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.7.5
      - name: Check clippy
        run: cargo clippy --all-features --all-targets -- -D warnings
